// app/layout.tsx
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import ClientLayout from "./client-layout";
import "@ant-design/v5-patch-for-react-19";
import "@/styles/globals.css";
import "@/styles/index.css";
import { Providers } from "./providers";
import { TopLoader } from "@/components/ui/ProgressBar";
import NetworkChecker from "@/components/ui/NetworkChecker";
import { Suspense } from "react";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={openSans.variable}>
      <body className="antialiased font-sans">
        <Providers>
          <NetworkChecker />
          <Suspense fallback={null}>
            <TopLoader />
          </Suspense>
          <ClientLayout>{children}</ClientLayout>
        </Providers>
      </body>
    </html>
  );
}
