"""add_extractor_tables

Revision ID: 157e3a2d498f
Revises: 9eca0eb5aaea
Create Date: 2025-12-31 14:59:54.080961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '157e3a2d498f'
down_revision: Union[str, Sequence[str], None] = '9eca0eb5aaea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('application_number', sa.String(length=50), nullable=False),
    sa.Column('doc_type', sa.String(length=100), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_application_number'), 'documents', ['application_number'], unique=False)
    op.create_index(op.f('ix_documents_doc_type'), 'documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_documents_file_id'), 'documents', ['file_id'], unique=True)
    op.create_table('document_extracted_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('ai_parsed_output', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('original_path', sa.String(length=500), nullable=True),
    sa.Column('ocr_json_path', sa.String(length=500), nullable=True),
    sa.Column('original_llm_path', sa.String(length=500), nullable=True),
    sa.Column('parsed_llm_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_ocr_text',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('ocr_text', sa.Text(length=16000000), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person_identity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('dob_year', sa.String(length=4), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('identity_number', sa.String(length=100), nullable=True),
    sa.Column('identity_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_identity_identity_number'), 'person_identity', ['identity_number'], unique=False)
    op.create_index(op.f('ix_person_identity_name'), 'person_identity', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_identity_name'), table_name='person_identity')
    op.drop_index(op.f('ix_person_identity_identity_number'), table_name='person_identity')
    op.drop_table('person_identity')
    op.drop_table('document_ocr_text')
    op.drop_table('document_files')
    op.drop_table('document_extracted_data')
    op.drop_index(op.f('ix_documents_file_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_application_number'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
