"""Add foreclosure and soa models

Revision ID: 315204baf68d
Revises: b51590970d61
Create Date: 2026-02-06 18:37:20.223347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '315204baf68d'
down_revision: Union[str, Sequence[str], None] = 'b51590970d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_ocr_text', 'ocr_text',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16000000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_ocr_text', 'ocr_text',
               existing_type=sa.Text(length=16000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
