"""rename assigned_at to assigned_date and update enums

Revision ID: 689deb7e699b
Revises: 371aed37a7e6
Create Date: 2026-02-12 11:58:20.709493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '689deb7e699b'
down_revision: Union[str, Sequence[str], None] = '371aed37a7e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('assigned_date', sa.DateTime(), nullable=True))
    op.alter_column('applications', 'process_status',
               existing_type=mysql.ENUM('New', 'In-Process', 'Completed', 'On-Hold'),
               type_=sa.Enum('New', 'In-Process', 'Completed', 'On-Hold', 'Pending', 'Rejected'),
               existing_nullable=False)
    op.drop_column('applications', 'assigned_at')
    # Duplicate state column in property_info (if it exists)
    # op.drop_column('property_info', 'state') # Wait, I need to be careful here. 
    # Usually there is only one state column in DB if it was created from model.
    # But if there were two in model, maybe one was never created.
    
    op.alter_column('document_ocr_text', 'ocr_text',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16000000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_ocr_text', 'ocr_text',
               existing_type=sa.Text(length=16000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.add_column('applications', sa.Column('assigned_at', mysql.DATETIME(), nullable=True))
    op.drop_column('applications', 'assigned_date')
    # ### end Alembic commands ###
