"""Add pan columns to extracted_loan_agreements

Revision ID: 9496f136c08f
Revises: 689deb7e699b
Create Date: 2026-02-13 00:33:07.534553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9496f136c08f'
down_revision: Union[str, Sequence[str], None] = '689deb7e699b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_ocr_text', 'ocr_text',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16000000),
               existing_nullable=True)
    op.add_column('extracted_loan_agreements', sa.Column('borrower_pan', sa.String(length=50), nullable=True))
    op.add_column('extracted_loan_agreements', sa.Column('co_borrower_1_pan', sa.String(length=50), nullable=True))
    op.add_column('extracted_loan_agreements', sa.Column('co_borrower_2_pan', sa.String(length=50), nullable=True))
    op.add_column('extracted_loan_agreements', sa.Column('co_borrower_3_pan', sa.String(length=50), nullable=True))
    op.add_column('extracted_loan_agreements', sa.Column('co_borrower_4_pan', sa.String(length=50), nullable=True))
    op.add_column('extracted_loan_agreements', sa.Column('co_borrower_5_pan', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extracted_loan_agreements', 'co_borrower_5_pan')
    op.drop_column('extracted_loan_agreements', 'co_borrower_4_pan')
    op.drop_column('extracted_loan_agreements', 'co_borrower_3_pan')
    op.drop_column('extracted_loan_agreements', 'co_borrower_2_pan')
    op.drop_column('extracted_loan_agreements', 'co_borrower_1_pan')
    op.drop_column('extracted_loan_agreements', 'borrower_pan')
    op.alter_column('document_ocr_text', 'ocr_text',
               existing_type=sa.Text(length=16000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
