"""Initial_migration

Revision ID: 9eca0eb5aaea
Revises: 
Create Date: 2025-12-31 13:43:41.514091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eca0eb5aaea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=True),
    sa.Column('business_code', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('Draft', 'Submitted', 'In-Review', 'Approved', 'Rejected'), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_business_code'), 'applications', ['business_code'], unique=True)
    op.create_index(op.f('ix_applications_record_id'), 'applications', ['record_id'], unique=True)
    op.create_table('loan_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=True),
    sa.Column('loan_requester_name', sa.String(length=200), nullable=True),
    sa.Column('loan_request_amount', sa.BigInteger(), nullable=True),
    sa.Column('loan_request_date', sa.DateTime(), nullable=True),
    sa.Column('pre_approval_amount', sa.BigInteger(), nullable=True),
    sa.Column('pre_approval_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['applications.record_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=True),
    sa.Column('file_uid', sa.String(length=200), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['applications.record_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=True),
    sa.Column('property_type', sa.String(length=100), nullable=True),
    sa.Column('survey_no', sa.String(length=50), nullable=True),
    sa.Column('subdivision', sa.String(length=100), nullable=True),
    sa.Column('plot_number', sa.String(length=50), nullable=True),
    sa.Column('door_number', sa.String(length=100), nullable=True),
    sa.Column('building_name', sa.String(length=200), nullable=True),
    sa.Column('floor', sa.String(length=50), nullable=True),
    sa.Column('appartment_size', sa.String(length=100), nullable=True),
    sa.Column('uds', sa.String(length=100), nullable=True),
    sa.Column('rera_no', sa.String(length=100), nullable=True),
    sa.Column('rera_status', sa.String(length=100), nullable=True),
    sa.Column('promotor', sa.String(length=255), nullable=True),
    sa.Column('name_of_the_project', sa.String(length=255), nullable=True),
    sa.Column('property_street', sa.Text(), nullable=True),
    sa.Column('property_locality', sa.String(length=255), nullable=True),
    sa.Column('property_town', sa.String(length=255), nullable=True),
    sa.Column('taluk', sa.String(length=255), nullable=True),
    sa.Column('village', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('zone', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('extent', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.String(length=100), nullable=True),
    sa.Column('longitude', sa.String(length=100), nullable=True),
    sa.Column('plan_approval_status', sa.String(length=100), nullable=True),
    sa.Column('plan_approval_number', sa.String(length=100), nullable=True),
    sa.Column('building_year', sa.String(length=20), nullable=True),
    sa.Column('building_value', sa.BigInteger(), nullable=True),
    sa.Column('property_tax_number', sa.String(length=100), nullable=True),
    sa.Column('waterconnection_number', sa.String(length=100), nullable=True),
    sa.Column('electricity_connection_number', sa.String(length=100), nullable=True),
    sa.Column('sro_office', sa.String(length=200), nullable=True),
    sa.Column('patta_number', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['applications.record_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_info')
    op.drop_table('property_images')
    op.drop_table('loan_info')
    op.drop_index(op.f('ix_applications_record_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_business_code'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
