"""add_father_name_and_address_to_application_context

Revision ID: b51590970d61
Revises: e63710bf7ffb
Create Date: 2025-12-31 15:37:36.009497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b51590970d61'
down_revision: Union[str, Sequence[str], None] = 'e63710bf7ffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_context', sa.Column('father_name', sa.String(length=255), nullable=True))
    op.add_column('application_context', sa.Column('address', sa.Text(), nullable=True))
    op.alter_column('document_ocr_text', 'ocr_text',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16000000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_ocr_text', 'ocr_text',
               existing_type=sa.Text(length=16000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_column('application_context', 'address')
    op.drop_column('application_context', 'father_name')
    # ### end Alembic commands ###
