"""add soa foreclosure and property fields to generated_report

Revision ID: e618b309f51d
Revises: 315204baf68d
Create Date: 2026-02-07 23:26:31.957905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e618b309f51d'
down_revision: Union[str, Sequence[str], None] = '315204baf68d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_ocr_text', 'ocr_text',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16000000),
               existing_nullable=True)
    op.add_column('generated_reports', sa.Column('survey_no', sa.String(length=100), nullable=True))
    op.add_column('generated_reports', sa.Column('plot_number', sa.String(length=100), nullable=True))
    op.add_column('generated_reports', sa.Column('door_number', sa.String(length=100), nullable=True))
    op.add_column('generated_reports', sa.Column('property_street', sa.Text(), nullable=True))
    op.add_column('generated_reports', sa.Column('property_locality', sa.String(length=255), nullable=True))
    op.add_column('generated_reports', sa.Column('property_town', sa.String(length=255), nullable=True))
    op.add_column('generated_reports', sa.Column('taluk', sa.String(length=255), nullable=True))
    op.add_column('generated_reports', sa.Column('village', sa.String(length=255), nullable=True))
    op.add_column('generated_reports', sa.Column('district', sa.String(length=255), nullable=True))
    op.add_column('generated_reports', sa.Column('pincode', sa.String(length=20), nullable=True))
    op.add_column('generated_reports', sa.Column('soa_bank_name', sa.String(length=255), nullable=True))
    op.add_column('generated_reports', sa.Column('soa_loan_account_number', sa.String(length=100), nullable=True))
    op.add_column('generated_reports', sa.Column('soa_sanction_date', sa.Date(), nullable=True))
    op.add_column('generated_reports', sa.Column('soa_sanction_amount', sa.String(length=50), nullable=True))
    op.add_column('generated_reports', sa.Column('soa_disbursed_amount', sa.String(length=50), nullable=True))
    op.add_column('generated_reports', sa.Column('soa_interest_rate', sa.String(length=50), nullable=True))
    op.add_column('generated_reports', sa.Column('soa_loan_status', sa.String(length=100), nullable=True))
    op.add_column('generated_reports', sa.Column('foreclosure_bank_name', sa.String(length=255), nullable=True))
    op.add_column('generated_reports', sa.Column('foreclosure_loan_account_number', sa.String(length=100), nullable=True))
    op.add_column('generated_reports', sa.Column('foreclosure_outstanding_principal', sa.String(length=50), nullable=True))
    op.add_column('generated_reports', sa.Column('foreclosure_total_amount_payable', sa.String(length=50), nullable=True))
    op.add_column('generated_reports', sa.Column('foreclosure_valid_upto_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_reports', 'foreclosure_valid_upto_date')
    op.drop_column('generated_reports', 'foreclosure_total_amount_payable')
    op.drop_column('generated_reports', 'foreclosure_outstanding_principal')
    op.drop_column('generated_reports', 'foreclosure_loan_account_number')
    op.drop_column('generated_reports', 'foreclosure_bank_name')
    op.drop_column('generated_reports', 'soa_loan_status')
    op.drop_column('generated_reports', 'soa_interest_rate')
    op.drop_column('generated_reports', 'soa_disbursed_amount')
    op.drop_column('generated_reports', 'soa_sanction_amount')
    op.drop_column('generated_reports', 'soa_sanction_date')
    op.drop_column('generated_reports', 'soa_loan_account_number')
    op.drop_column('generated_reports', 'soa_bank_name')
    op.drop_column('generated_reports', 'pincode')
    op.drop_column('generated_reports', 'district')
    op.drop_column('generated_reports', 'village')
    op.drop_column('generated_reports', 'taluk')
    op.drop_column('generated_reports', 'property_town')
    op.drop_column('generated_reports', 'property_locality')
    op.drop_column('generated_reports', 'property_street')
    op.drop_column('generated_reports', 'door_number')
    op.drop_column('generated_reports', 'plot_number')
    op.drop_column('generated_reports', 'survey_no')
    op.alter_column('document_ocr_text', 'ocr_text',
               existing_type=sa.Text(length=16000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
