"""rename_person_identity_to_application_context

Revision ID: e63710bf7ffb
Revises: 157e3a2d498f
Create Date: 2025-12-31 15:32:56.453784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e63710bf7ffb'
down_revision: Union[str, Sequence[str], None] = '157e3a2d498f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_context',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('dob_year', sa.String(length=4), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('identity_number', sa.String(length=100), nullable=True),
    sa.Column('identity_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_context_identity_number'), 'application_context', ['identity_number'], unique=False)
    op.create_index(op.f('ix_application_context_name'), 'application_context', ['name'], unique=False)
    op.drop_index(op.f('ix_person_identity_identity_number'), table_name='person_identity')
    op.drop_index(op.f('ix_person_identity_name'), table_name='person_identity')
    op.drop_table('person_identity')
    op.alter_column('document_ocr_text', 'ocr_text',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16000000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_ocr_text', 'ocr_text',
               existing_type=sa.Text(length=16000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.create_table('person_identity',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('dob_year', mysql.VARCHAR(length=4), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('identity_number', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('identity_type', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('person_identity_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_person_identity_name'), 'person_identity', ['name'], unique=False)
    op.create_index(op.f('ix_person_identity_identity_number'), 'person_identity', ['identity_number'], unique=False)
    op.drop_index(op.f('ix_application_context_name'), table_name='application_context')
    op.drop_index(op.f('ix_application_context_identity_number'), table_name='application_context')
    op.drop_table('application_context')
    # ### end Alembic commands ###
